### ISSUE TITLE
Library use cases and purpose?

### ISSUE THREAD

**Issue by markerikson** [MrEfrem/redux-fly#1]
Hi.  You've got a bunch of interesting code going on here.  Skimming through it, it looks like you're implementing something along the lines of encapsulated components and Redux reducer logic.  Any chance you could put up a description of what the library is intended to do and how to use it?

**Comment by MrEfrem** [comment]
Hello.
Yes at me in plans to write the description and to make examples of use. Only I not up to the end finished with API therefore there can be serious changes.
The purpose of library to make uses of redux same it is simple as a native state of the React components, but to expand these opportunities that it was possible to interact between components through redux action.

**Comment by MrEfrem** [comment]
I added description, examples and to stabilized api. Will be soon is stable reliase.
